### ISSUE TITLE
Hatchery: Add the ability to choose the sorting attribute

### ISSUE THREAD

**Issue by Farigh** [Farigh/pokeclicker-automation#48]
### Is your feature request related to a problem? Please describe.
In some cases, the player might want to focus on breeding a particular pokemon type.
The current implementation only allows breeding efficiency sorting and shiny pokemon filtering.

### Describe the solution you'd like
Add a dedicated menu for hatchery where the player can fine-tune the breeding parameters.

### Additional context
Suggested by #43

---

Todo:

- [X] ~Prioritize by type~ (#129)
- [ ] Prioritize by EVs
- [X] ~Prioritize by region~ (#114)
- [X] ~Prioritize by regional debuff~ (#114)
- [ ] Sort by other properties than Breeding efficiency

**Comment by Farigh** [comment]
suggested in #43 : Region sorting

**Comment by Farigh** [comment]
Suggested on reddit by `darthcid`: Type sorting

**Comment by Farigh** [comment]
Suggested by #101 : Consider EVs priorizing

**Comment by Daniferrito** [comment]
If I understand it right, the request from #101 is to have the breeding efficiency formula (optionally) ignore EVs when calculating the breeding efficiency.

Is this correct? It says "Prioritize by EVs" in the checklist at the top, which suggests something else.

The first half of #101 is already implemented in #197 (or at least the same sorting criterias that are shown in the Day Care modal, for "hatch legendaries first", the game does not even store whether a pokemon is a legendary or not)

**Comment by Daniferrito** [comment]
Do we want to also add a filter to consider alternate forms last?
Just like consider shiny pokemon last, it helps to farm the shiny pokedex archievements.

It is trivial to include into #197, but might be too many options for the UI, that is why I'm asking

**Comment by Daniferrito** [comment]
I included it into the PR, but feel free to remove it.

There are two cases that it does not cover:
* Sevii shiny pokedex. This is special, as it covers ONLY alternate forms.
* Already have a shiny alternate form, but not the base one.

For the first case, the player can simply go for all pokemons with alternative forms for Kanto. It includes a few uneeded ones, but not that many.
For the second case, a check could be added to check if any alternate form is shiny and count it as shiny as well, but that is a much more expensive calculation to perform, and not worth it.
